docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com
  script:
    - docker build --pull -t registry.gitlab.com/mobina/loghmeh .
    - docker push registry.gitlab.com/mobina/loghmeh
  only:
    - back-end