apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: registry.gitlab.com/mobina/loghmeh:back
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 0.2
            memory: "220Mi"
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    app: back
spec:
  type: NodePort
  selector:
    app: back
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32013
