apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: registry.gitlab.com/mobina/loghmeh:front
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 0.2
            memory: "40Mi"
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31013
