apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
  host: loghmeh-mysql
  name: Loghmeh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: loghmeh-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loghmeh-mysql
  labels:
    app: loghmeh-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: loghmeh-mysql
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghmeh-mysql
  labels:
    app: loghmeh-mysql
spec:
  selector:
    matchLabels:
      app: loghmeh-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loghmeh-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: 0.2
            memory: "400Mi"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: config-volume
